Create join quiz page
Team-Chicken-Nuggets/quizem-frontend pull request #1
Opened 2021-04-16 01:22 UTC by BenLanglois

Created:

- Join quiz page
- Button component
- Text input component

https://user-images.githubusercontent.com/28707918/114957897-ece4c800-9e2f-11eb-8868-647dc5b03218.mp4

2021-04-16 02:55 UTC, alexgirard requested changes
Looks amazing!

2021-04-16 02:55 UTC, alexgirard commented on src/student/JoinQuizPage.tsx
> +        <TitleText color="white">quizem</TitleText>
since the student side has a similar design for all screens I think the outline and title should be extracted into a wrapper component!

2021-04-16 02:55 UTC, alexgirard commented on src/student/JoinQuizPage.tsx
> +            <VSpace height="0.5em" />
nit but instead of vspace here maybe we could create a grid/rows/columns component that specifies a grid/row/column gap between all child elements for consistency?

2021-04-16 02:55 UTC, alexgirard commented on src/index.html
> +  <title>TITLE HERE</title>
```suggestion
  <title>Quizem</title>
```

2021-04-16 02:55 UTC, alexgirard commented on src/components/Colors.ts
> +export const white = '#FFFFFF';
super nit: personally instead of colors & container files I prefer to use [Styled System](https://styled-system.com/) in which you can specify theme colors, padding, responsive behaviour, etc.  I find it quite nice to really abstract components (ex. Input) Not sure if you've heard about it,, if you like it I'd consider setting it up

2021-04-16 02:55 UTC, alexgirard commented on src/components/Input.tsx
> +export const Input = (props: Props) => {
💯 1

2021-04-17 02:42 UTC, ariellam reviewed
just one comment, otherwise looks good!

2021-04-17 02:42 UTC, ariellam commented on src/student/JoinQuizPage.tsx
> +  background-color: #133ba8;
Can we add this to the `Colors` file?

2021-04-17 15:35 UTC, BenLanglois commented on src/components/Colors.ts
> +export const white = '#FFFFFF';
I haven't heard of this before. I'd be willing to try it out! Maybe out of scope for this PR though.

2021-04-17 15:36 UTC, BenLanglois commented on src/student/JoinQuizPage.tsx
> +        <TitleText color="white">quizem</TitleText>
Good idea. I'll probably add the background to this component too, since all screens will eventually need the blobs.

2021-04-17 15:42 UTC, BenLanglois commented on src/student/JoinQuizPage.tsx
> +  background-color: #133ba8;
We might remove the colours file eventually in favour of styled system, but I'll add it for now.

2021-04-17 16:10 UTC, BenLanglois commented on src/student/JoinQuizPage.tsx
> +            <VSpace height="0.5em" />
I refactored this a bit. Still using flexbox, but I added margins to the child elements instead.

2021-04-17 19:12 UTC, alexgirard approved these changes
lgtm!

2021-04-17 20:19 UTC, merged