[stu] Create waiting page
Team-Chicken-Nuggets/quizem-frontend pull request #2
Opened 2021-04-17 15:59 UTC by ariellam

Adds the waiting page for students.

<img width="498" alt="Screen Shot 2021-04-17 at 11 31 13 AM" src="https://user-images.githubusercontent.com/16458871/115118987-26265080-9f74-11eb-8c97-3652656b663d.png">

Will rebase off of `main` once `login-page` has been merged!

2021-04-17 17:29 UTC, BenLanglois requested changes
Looks good. I added more to the `login-page` branch, so maybe set that branch as the target instead of `main`.

2021-04-17 17:29 UTC, BenLanglois commented on src/student/WaitingPage.tsx
> +        <TitleText color="white">quizem</TitleText>
I created a `StudentPageBase` component in the `login-page` branch that could be used here.

2021-04-17 20:20 UTC, BenLanglois commented
> Looks good. I added more to the `login-page` branch, so maybe set that branch as the target instead of `main`.

That branch has been merged into main now, so don't worry about changing the base anymore.

2021-04-18 01:07 UTC, ariellam commented
> > Looks good. I added more to the `login-page` branch, so maybe set that branch as the target instead of `main`.
> 
> That branch has been merged into main now, so don't worry about changing the base anymore.

Cool, I'll rebase from main!

2021-04-18 16:51 UTC, alexgirard commented on src/student/WaitingPage.tsx
> +        <TitleText color="white">quizem</TitleText>
+1

2021-04-23 06:22 UTC, BenLanglois approved these changes

2021-04-23 15:57 UTC, merged