QUIZ-89 Create graph question state
Team-Chicken-Nuggets/quizem-frontend pull request #28
Opened 2021-06-10 05:13 UTC by ariellam

Displays the graph and live question view when `Send Question` is pressed. I've also added a placeholder text for the timer/count space until QUIZ-87 is complete. 

This PR only covers the UI – I've added a dummy data object to pass to the graph until we can query for the quiz data. 
 
<img width="946" alt="Screen Shot 2021-06-10 at 1 04 34 AM" src="https://user-images.githubusercontent.com/16458871/121468222-6dcfc400-c988-11eb-8c10-270c1fc392e8.png">

2021-06-11 15:58 UTC, heathermusson commented on src/instructor/QuestionDetails.tsx
> +        </StretchColumn>
Can we please move all of the graph components to a separate graph component? Having a separate graph component will allow us to keep all of the graph logic in its own area instead of bloating this componeont.

2021-06-11 16:00 UTC, heathermusson requested changes
Some UI questions:
1. What do you do if the responses have text (ie. "some response option" instead of "A")? Like what do we show in the graph state?
2. Is there a way to go back and see the question creation view? I don't think they should be able to edit that info, but it might be useful if people want to go back and check what the response options were.

2021-06-12 04:59 UTC, alexgirard commented
+1 to heathers first question, and to the second there currently is no way - we should open up a ticket for that. Also is there a way to colour the correct answer green in the graph?

2021-06-16 20:22 UTC, ariellam commented
> 1. What do you do if the responses have text (ie. "some response option" instead of "A")? Like what do we show in the graph state?
From the `Data` object in `MultipleChoiceGraph`, we only have `letter` and `count` fields, so the graph displays the letter as the label and the count on the graph. As of right now, we're using the mock data that matches this `Data` structure for the graph, and not the option labels. 

I think this could be a separate ticket as we may have to refactor the graph to support this? Let me know what y'all think. 

> 2. Is there a way to go back and see the question creation view? I don't think they should be able to edit that info, but it might be useful if people want to go back and check what the response options were.

Mentioned in last meeting and will be addressed in [QUIZ-97](https://quizem.atlassian.net/browse/QUIZ-97)!

2021-06-17 20:51 UTC, ariellam commented
I've added the correct answer to the graph, so now it should appear on the chart:

<img width="782" alt="Screen Shot 2021-06-17 at 4 49 41 PM" src="https://user-images.githubusercontent.com/16458871/122470615-454d5880-cf8c-11eb-8b40-e4b95d7cfd7f.png">

2021-06-17 23:47 UTC, alexgirard commented on src/instructor/QuestionDetails.tsx
> +  const [isQuestionLive, setIsQuestionLive] = useState(false);
I think we should be pulling this in from gql?

2021-06-19 04:13 UTC, ariellam commented on src/instructor/QuestionDetails.tsx
> +  const [isQuestionLive, setIsQuestionLive] = useState(false);
I think the `addQuestion` and `editQuestion` queries don't have the right input type, and we're getting an error in graphql which isn't adding the questions to the backend.

2021-06-22 02:58 UTC, alexgirard approved these changes

2021-06-22 17:13 UTC, merged