QUIZ-87 Timer and response components
Team-Chicken-Nuggets/quizem-frontend pull request #29
Opened 2021-06-11 06:16 UTC by ariellam

Adds the timer and response UI components.

<img width="959" alt="Screen Shot 2021-06-11 at 2 08 47 AM" src="https://user-images.githubusercontent.com/16458871/121639164-231e7c80-ca5a-11eb-8507-713d1acef586.png">

2021-06-11 15:46 UTC, heathermusson requested changes
Looks good, just one comment.

2021-06-11 15:46 UTC, heathermusson commented on src/instructor/QuestionDetails.tsx
> +                responseCount={dummyData.reduce(function (a, b) {
I'll add a `totalResponses` field to the backend, so this will eventually be easier.

2021-06-11 15:46 UTC, heathermusson commented on src/instructor/Timer.tsx
> +  }
This will start the counter from the first time the instructor chooses to view the graph. I think it would be better to query the [start time of the live question](https://github.com/Team-Chicken-Nuggets/server/blob/main/app/graphql/types/live_question_type.rb) and use the difference between that time and `now` to start the counter. 

To clarify, we shouldn't query the start time every second. Only query it once and use the difference to set the initial time counter.

2021-06-12 05:04 UTC, alexgirard requested changes

2021-06-12 05:04 UTC, alexgirard commented on src/instructor/QuestionDetails.tsx
> +                }, 0)}
```suggestion
                responseCount={dummyData.reduce((a, b) => a + b.count, 0)}
```

2021-06-12 05:04 UTC, alexgirard commented on src/instructor/Responses.tsx
> +const ResponsesWrapper = styled(CenteredContainer)`
I would separate this ResponsesWrapper and TimerWrapper into a separate UI component (`Pill` maybe?)  and remove the minWidth - not necessary with padding

2021-06-17 16:38 UTC, ariellam commented on src/instructor/Timer.tsx
> +  }
Okay cool, this works for me and is definitely easier to calculate the difference.

2021-06-19 02:20 UTC, ariellam commented on src/instructor/Responses.tsx
> +const ResponsesWrapper = styled(CenteredContainer)`
For the `minWidth` on both the timer / responses, I added it to prevent jittering when more responses are added – I think I can take out the width padding for both though! 

![2021-06-18 21 45 56](https://user-images.githubusercontent.com/16458871/122628291-4d3bf400-d083-11eb-992c-dd1e21fd3132.gif)

(sorry for the watermark lmaoo)

2021-06-22 03:06 UTC, alexgirard approved these changes

2021-06-22 17:11 UTC, merged