QUIZ-17 Multiple choice buttons
Team-Chicken-Nuggets/quizem-frontend pull request #4
Opened 2021-04-26 04:05 UTC by BenLanglois

Created multiple choice buttons with and without labels.

<img height="600" src="https://user-images.githubusercontent.com/28707918/116027316-870ff180-a622-11eb-8674-b0cc10d88c1e.png" />

2021-04-26 15:09 UTC, heathermusson commented
Question, why are the 'C' and 'D' smaller in the preview image?

2021-04-26 15:10 UTC, heathermusson commented on src/student/MultipleChoicePage.tsx
> +        />
Can we make this read values from an array? It will make it easier when we are getting values from the server.

2021-04-26 15:28 UTC, BenLanglois commented
Discussed in today's meeting, the design of the labelled buttons will change. I'll update the PR shortly.

2021-04-27 19:48 UTC, alexgirard commented on src/student/MultipleChoicePage.tsx
> +        />
+1 -> I would iterate over the "options" (in my pr I used { label?:  string, correct?: boolean }[]) and then render the MultipleChoiceButton component

2021-04-27 19:48 UTC, alexgirard commented on src/components/LabelledMultipleChoiceButton.tsx
> +        <MediumText>{props.letter}</MediumText>
the font size for the labelled button ABCD label looked a bit small to me

2021-04-27 20:44 UTC, BenLanglois commented on src/student/MultipleChoicePage.tsx
> +        />
Okay, but I think this will be a second component, e.g. `MultipleChoiceButtonsList`

2021-04-27 21:01 UTC, BenLanglois commented
> Question, why are the 'C' and 'D' smaller in the preview image?

They're smaller because they have labels (while 'A' and 'B' don't), which follows the design sketch. This will still be true with the labelled button redesign.

2021-04-27 21:02 UTC, BenLanglois commented on src/components/LabelledMultipleChoiceButton.tsx
> +        <MediumText>{props.letter}</MediumText>
I'll bump up the font size

2021-04-29 01:45 UTC, ariellam reviewed
Looks good! Just wondering if we were going to put the question text on the Student view (like in the Figma mocks) or if that was for another PR?

2021-04-29 01:45 UTC, ariellam commented on src/index.html
> +  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
good catch!

2021-05-01 05:12 UTC, BenLanglois commented on src/student/MultipleChoicePage.tsx
> +        />
Created lists of multiple choice buttons in #9

2021-05-05 00:32 UTC, heathermusson requested changes

2021-05-05 00:32 UTC, heathermusson commented on src/components/Colors.ts
>  export const darkBlue = '#133BA8';
I'm not familiar with styled system (@alexgirard maybe you could provide some info here?), but are these colours no longer needed now (ie. can be replaced by styled system)?

2021-05-05 00:32 UTC, heathermusson commented on src/student/MultipleChoicePage.tsx
> +      </LabelledButtonContainer>
I think we need to rework how we are displaying the multiple-choice buttons. These questions/suggestions are all my opinion so feel free to disagree.

1. I think we should have a universal multiple-choice button component. This component should have an optional text prop. Maybe within this component will have a labelled/unlabeled component, but I think the "higher-level" component should be universal between options with or without a label. We might even need separate components and could just display the label if it is provided. Overall, I think we would benefit from a more universal component.
2. What are the LabelledButtonContainer and UnlabelledButtonContainer? I think these should be moved within the button components.

2021-05-05 20:00 UTC, alexgirard commented on src/components/Colors.ts
>  export const darkBlue = '#133BA8';
this mr needs to be rebased! there's a bunch of changes on master regarding styled system and colouring

2021-05-05 20:09 UTC, alexgirard commented on src/student/MultipleChoicePage.tsx
> +      </LabelledButtonContainer>
I think 2 is taken care of in pr #9 and I do agree with 1! in this case we can create a wapper component for both multiple-choice list components which determines which one to used based on the input. For example, if all options don't have labels show the square buttons. In the case where some answers have labels and others don't we should show the labelled buttons (maybe with placeholder text?? idk)

2021-05-06 19:37 UTC, BenLanglois commented on src/student/MultipleChoicePage.tsx
> +      </LabelledButtonContainer>
1. I agree, but I think that should be addressed in #9, not here.
2. These are just temporary containers to show off the buttons, they're removed in #9.

2021-05-11 01:00 UTC, heathermusson approved these changes

2021-05-11 20:48 UTC, merged