QUIZ-15 [instr] Create landing page
Team-Chicken-Nuggets/quizem-frontend pull request #5
Opened 2021-04-26 07:33 UTC by ariellam

Adds landing page for instructors (only desktop-friendly atm!).
<img width="1226" alt="Screen Shot 2021-04-26 at 3 32 04 AM" src="https://user-images.githubusercontent.com/16458871/116045510-1bd51800-a640-11eb-85ef-71e8f41b516a.png">

2021-04-27 21:32 UTC, BenLanglois requested changes
It looks like there are a few compiler/linter errors. Could you run `yarn build-dev` and `yarn lint-fix` and fix them?

2021-04-27 21:32 UTC, BenLanglois commented on src/components/Button.tsx
> +  min-height: ${props => (props.height ? props.height : 3.625)}em;
Is this conditional check necessary? `props.height` isn't optional, and I don't think it should be 0 either.

2021-04-27 21:32 UTC, BenLanglois commented on src/instructor/LandingPage.tsx
> +`;
Nit: empty style, you can just use `Button` directly.

As an aside, I wonder if there's a linter rule to catch this?

2021-04-28 13:48 UTC, alexgirard requested changes

2021-04-28 13:48 UTC, alexgirard commented on src/instructor/LandingPage.tsx
> +                  // noop
you can reroute to the join room student view page here

2021-04-28 13:48 UTC, alexgirard commented on src/instructor/LandingPage.tsx
> +                  // noop
you can reroute to the create quiz page here

2021-04-28 13:48 UTC, alexgirard commented on src/components/InstructorPageBase.tsx
> +import React from 'react';
I would personally remove this component and move all the styling into the landing page since the landing page has a unique design from the rest of the site (no reused components)

2021-04-28 13:48 UTC, alexgirard commented on src/components/Button.tsx
> +  padding: 0.5em ${props => (props.hPadding ? props.hPadding : 3)}em;
I think padding ideally should be kept consistent throughout all buttons, instead of the `hPadding` prop maybe just adjust the value? Also after adding styled-system in [this pr](https://github.com/Team-Chicken-Nuggets/quizem-frontend/pull/6) I added some button variants in theme.js which should take care of the different button styles! you will just need to import border, color & space from styled-system and inline it in the styled component

2021-04-29 02:10 UTC, ariellam commented on src/instructor/LandingPage.tsx
> +`;
Ah yeah I think I was going to add additional styles in but ended up not using it

2021-04-29 15:03 UTC, alexgirard approved these changes
looks good for now, I would merge in now and we can refactor to use styled system after

2021-04-29 15:03 UTC, alexgirard commented on src/instructor/LandingPage.tsx
> +const ButtonLink = styled(Link)`
nit: move the text-decoration styleinto Button itself

2021-04-29 19:07 UTC, ariellam commented
> looks good for now, I would merge in now and we can refactor to use styled system after

sure! think we're still waiting on @BenLanglois's review

2021-04-29 19:08 UTC, BenLanglois approved these changes

2021-04-29 19:08 UTC, BenLanglois commented on src/instructor/LandingPage.tsx
> +                      }}
I guess if we are intentionally leaving `onClick` as a no-op (because of `ButtonLink`) then we could make `onClick` optional in the `Button` props.

Probably not necessary to address that in this PR though.

2021-04-29 19:09 UTC, merged