Create quiz screen
Team-Chicken-Nuggets/quizem-frontend pull request #6
Opened 2021-04-27 19:42 UTC by alexgirard

### done
- adds styled system & create quiz components

### to do
- add quiz type icons
- add MC option styling

<img width="1141" alt="Screen Shot 2021-04-27 at 3 39 21 PM" src="https://user-images.githubusercontent.com/16641217/116302066-bdf31e00-a76e-11eb-882b-423a987c9f82.png">

2021-04-27 22:53 UTC, BenLanglois requested changes
It looks like there are a few compiler/linter errors. Could you run `yarn build-dev` and `yarn lint-fix` and fix them?

Also, in the future, could we try to keep PRs smaller? Just to make it easier to review 🙂

2021-04-27 22:53 UTC, BenLanglois commented on src/components/Toggle.tsx
> +const toggleBoxStyles = `
Styled components has a way to define styles that aren't linked to a class:

```typescript
import styled, { css } from 'styled-components';

const toggleBoxStyles = css`
  border-radius: 15px;
  /* ... */
`;

const ToggleLabel = styled.label`
  position: absolute;
  /* ... */
  ${toggleBoxStyles}
`;
```

Using the `css` object allows syntax highlighting and linting to still work just like it does with, say, `styled.div`.

2021-04-27 22:53 UTC, BenLanglois commented on src/components/Toggle.tsx
> +  const [id] = React.useState<string>(uniqueId('label-'));
Same as above: you shouldn't need to specify the type for `useState` here.

2021-04-27 22:53 UTC, BenLanglois commented on src/components/Toggle.tsx
> +  onClick: (value: boolean) => void;
Since the parent component passes `active` as a prop, it should already know whether or not the toggle is active when it is clicked, so you shouldn't need to pass the value of `active` back to the parent.

2021-04-27 22:53 UTC, BenLanglois commented on src/instructor/Preview.tsx
> +    selectedQuestion || selectedQuestion === 0
Nit: I prefer `selectedQuestion !== null`, I find it's a bit cleaner

2021-04-27 22:53 UTC, BenLanglois commented on src/instructor/Questions.tsx
> +  const [showOptionLabels, setShowOptionLabels] = React.useState<boolean>(false);
Nit: here too

2021-04-28 01:33 UTC, BenLanglois commented
From the image, it looks like the "add question" buttons don't use the correct font

2021-04-28 13:57 UTC, alexgirard commented on src/components/Button.tsx
> +    <Text variant="medium">{children}</Text>
So text has its own variants in which I'm specifying that button always wants medium text. The button variant is passed down in props to the button container

2021-04-28 13:58 UTC, alexgirard commented on src/components/Toggle.tsx
> +const toggleBoxStyles = `
cool didn't know that! will add

2021-04-28 14:00 UTC, alexgirard commented on src/components/Toggle.tsx
> +  onClick: (value: boolean) => void;
hmm yeah I suppose I was thinking that the toggle component would manage the state completely and only pass down the initial toggle state, but since we'll be updating it from the parent I'll just remove the state completely

2021-04-28 14:01 UTC, alexgirard commented on src/instructor/Preview.tsx
> +    selectedQuestion || selectedQuestion === 0
Yeah I was getting a weird type error when I tried that :'(

2021-04-28 14:01 UTC, alexgirard commented
> From the image, it looks like the "add question" buttons don't use the correct font

Sorry should have specified, the font is incorrect since it is just a placeholder right now for icons.

2021-04-29 18:01 UTC, heathermusson approved these changes

2021-04-29 18:02 UTC, alexgirard commented on src/components/Accordian.tsx
> +  outlined: boolean;
good call!

2021-04-29 18:03 UTC, alexgirard commented on assets/iPhoneFrame.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
I believe ariel just used pngs since the landing page shows just images with static inner content

2021-04-29 18:52 UTC, BenLanglois commented on src/components/Button.tsx
> +    <Text variant="medium">{children}</Text>
Okay, I'm not very familiar with styled system yet so I just wanted to make sure 👍

2021-04-29 19:00 UTC, BenLanglois approved these changes

2021-04-29 19:01 UTC, ariellam approved these changes
LGTM 👍, left a nit but otherwise everything is great!

2021-04-30 02:30 UTC, alexgirard commented on src/components/Accordian.tsx
> +export const Accordian = ({ title, outlined, onClick, children }: Props) => {
🤦

2021-04-30 02:32 UTC, merged