QUIZ-37 [instr] top bar
Team-Chicken-Nuggets/quizem-frontend pull request #7
Opened 2021-04-30 08:48 UTC by ariellam

Adds the top bar to the create quiz page, along with the room code. 
<img width="1221" alt="Screen Shot 2021-04-30 at 1 45 49 AM" src="https://user-images.githubusercontent.com/16458871/116671680-133d5400-a956-11eb-9244-3dc2d4b2d38e.png">
<img width="1221" alt="Screen Shot 2021-04-30 at 1 46 32 AM" src="https://user-images.githubusercontent.com/16458871/116671689-159fae00-a956-11eb-99a2-91e59858b548.png">

Also included changes to fix scrolling on the page, when content overflows.

2021-04-30 13:51 UTC, alexgirard requested changes
looks great so far!

2021-04-30 13:51 UTC, alexgirard commented on src/instructor/CreateQuizPage.tsx
> +const TopBarContainer = styled.div`
Can we remove `TopBarContainer` from this component and move `height: 5em` style to `Topbar`? also maybe we can make an `IntsructorPageBase` component that has the page wrapper and the Topbar?

2021-04-30 13:51 UTC, alexgirard commented on src/components/TopBar.tsx
> +          </QuizCodeParent>
Since this is the same as the input field Ben created for the student side, you can probably just use that component but disable any events so its display only

2021-04-30 13:51 UTC, alexgirard commented on src/components/TopBar.tsx
> +  quizCode: 'TEST',
I don't think we should have a default here in the case of errors, its probably best not to show the field at all if we haven't received a working code

2021-04-30 13:51 UTC, alexgirard commented on src/components/TopBar.tsx
> +      {/* TODO: Add start session animation with code */}
what does this comment refer to?

2021-04-30 13:51 UTC, alexgirard commented on src/components/TopBar.tsx
> +const LiveSessionContainer = styled(FlexContainer)`
the beautiful thing about styled system -> instead of styling `FlexContainer` you can just do this directly
```
<FlexContainer alignItems='center'>
```

2021-04-30 13:51 UTC, alexgirard commented on src/components/TopBar.tsx
> +  line-height: 100%;
same here -> 
```
<Text lineHeight="100%">
```

2021-04-30 13:51 UTC, alexgirard commented on src/components/TopBar.tsx
> +const QuizCodeChild = styled(LeftAlignColumn)`
same here -> 
```
<LeftAlignColumnheight="40px">
```

2021-04-30 13:51 UTC, alexgirard commented on src/instructor/CreateQuizPage.tsx
> +  padding-top: 9em;
Same here for QuizContainer & PreviewContainer -> 
```
<StretchColumn pt="9em">
           &
<PreviewContainer pt="9em">
```

2021-04-30 13:51 UTC, alexgirard commented on src/instructor/PhonePreview.tsx
> +  position: sticky;
ty 🙌

2021-04-30 18:45 UTC, ariellam commented on src/components/TopBar.tsx
> +      {/* TODO: Add start session animation with code */}
I think it'd be nice to slide out the code from the button when the session is started – totally extra tho not for this PR :)

2021-04-30 23:36 UTC, ariellam commented on src/instructor/CreateQuizPage.tsx
> +const TopBarContainer = styled.div`
good idea!

2021-05-01 02:50 UTC, alexgirard requested changes
small notes for reusability :)

2021-05-01 02:50 UTC, alexgirard commented on src/components/InstructorPageBase.tsx
> +    <TopBar isLive />
wont this always return true?

2021-05-01 02:50 UTC, alexgirard commented on src/components/TopBar.tsx
> +        )}
I would move all this logic outside the topbar component, and put it in create quiz so that the library screens can use this component as well! maybe pass this as children to the component and justify space between the logo and component children?

2021-05-01 17:27 UTC, ariellam commented on src/components/TopBar.tsx
> +        )}
good idea! makes sense and we can also use it for the landing page

2021-05-01 18:01 UTC, alexgirard approved these changes
small comment otherwise looks good!

2021-05-01 18:01 UTC, alexgirard commented on src/instructor/CreateQuizPage.tsx
> +        <CenteredRow mr="2em">
instead of CenteredRow you can just do 
```
<FlexContainer alignItems="center" gridGap={3}>
```
and remove CenteredRow  completely

2021-05-01 19:52 UTC, alexgirard commented on src/instructor/CreateQuizPage.tsx
> +export const CreateQuizPage = ({ isLive, quizCode }: Props) => {
^ synced, this should be ok for now can we update `quizCode` to be `sessionCode` instead?

2021-05-04 21:46 UTC, ariellam commented on src/instructor/CreateQuizPage.tsx
> +export const CreateQuizPage = ({ isLive, quizCode }: Props) => {
sounds good, will make the change!

2021-05-05 00:14 UTC, merged