Multiple choice list
Team-Chicken-Nuggets/quizem-frontend pull request #9
Opened 2021-05-01 05:09 UTC by BenLanglois

Components to render a list of multiple choice buttons

2021-05-01 20:25 UTC, alexgirard requested changes

2021-05-01 20:25 UTC, alexgirard commented on src/student/MultipleChoicePage.tsx
> +      <LabelledMultipleChoiceList
I think since heathers implementation of options is 
```
answers {
    id 
    format
    identifier
    label
}
```
this component should sort the options by increasing `identifier`. Then they can be passed to `LabelledMultipleChoiceList`

2021-05-01 20:25 UTC, alexgirard commented on src/student/MultipleChoicePage.tsx
> +        questions={[
can we change this prop to `options` or `labels`

2021-05-01 20:25 UTC, alexgirard commented on src/student/multipleChoice/LabelledMultipleChoiceList.tsx
> +  if (choices < 1 || choices > 26) {
I'm assuming 26 for the number of letters? should we have a lower limit (ex. ~10)?

2021-05-01 20:25 UTC, alexgirard commented on src/student/multipleChoice/LabelledMultipleChoiceList.tsx
> +  for (let index = 0; index < choices; ++index) {
can we change this to use a `map` function iterating over `questions` (which can we rename questions?) then this can be
```
const buttons = props.questions.map(({ label, identifier }) => (
     <LabelledMultipleChoiceButton
          key={identifier}
          letter={identifier}
          label={label}
          color={props.color}
          isSelected={selected === identifier}
          onClick={() => {
            setSelected(identifier);
            props.onSelect(identifier);
          }}
      />
));
```

2021-05-01 20:25 UTC, alexgirard commented on src/student/multipleChoice/MultipleChoiceList.tsx
> +  for (let index = 0; index < props.choices; ++index) {
same thing here, can this instead use `map` ?

2021-05-05 00:37 UTC, heathermusson commented on src/util/index.ts
> +}
I like the use of the util file, but I think we should have different util files for different parts of the app. One massive util file seems messy for the long term. I think this file should be moved to closer to the multiple-choice components and called `MultipleChoiceUtils` or something similar.

2021-05-05 00:39 UTC, heathermusson commented on src/student/multipleChoice/MultipleChoiceList.tsx
> +    const letter = getNthLetter(index);
The letter will be provided by the server so this isn't needed. Furthermore, the letter prop on the component below should likely be called `identifier` to match the server.

2021-05-06 19:55 UTC, BenLanglois commented on src/student/MultipleChoicePage.tsx
> +      <LabelledMultipleChoiceList
Changed this in #4

2021-05-06 19:56 UTC, BenLanglois commented on src/student/multipleChoice/MultipleChoiceList.tsx
> +    const letter = getNthLetter(index);
Changed "letter" to "identifier" in #4

2021-05-07 00:02 UTC, BenLanglois commented on src/student/MultipleChoicePage.tsx
> +        questions={[
I agree that `questions` is misleading. I think I'll change it to answers to keep it the same as the graphQL api.

2021-05-07 00:03 UTC, BenLanglois commented on src/student/multipleChoice/LabelledMultipleChoiceList.tsx
> +  if (choices < 1 || choices > 26) {
This is no longer relevant since the identifier is being passed in as a prop.

2021-05-07 00:04 UTC, BenLanglois commented on src/util/index.ts
> +}
This is no longer relevant since I'm removing the util function because the identifier is being passed in as a prop.

2021-05-08 15:08 UTC, alexgirard approved these changes

2021-05-08 15:08 UTC, merged